name: commit-and-push

inputs:
    message:
        description: The commit message
        required: true
    github-token:
        description: The GitHub token
        required: false

runs:
    using: composite
    steps:
        - uses: actions/github-script@v7
          with:
              script: |
                  const run = require('./tools/gh-actions/commit-and-push/main.js');
                  const inputs = ${{ toJSON(inputs) }};

                  await run({ github, context, core, glob, io, exec, inputs });
