name: commit-and-push

inputs:
    message:
        description: The commit message
        required: true
    setup-git-user:
        description: Setup git user
        required: false
        default: 'false'

runs:
    using: composite
    steps:
        - uses: ./.github/actions/setup-git-user
          if: ${{ inputs.setup-git-user == 'true' }}
          with:
              name: 'github-actions[bot]'
              email: '41898282+github-actions[bot]@users.noreply.github.com'

        - shell: bash
          run: |
              git add .
              git commit -n -m "${{ inputs.message }}"
              git push origin $(git branch --show-current)
