name: demo

on:
    workflow_dispatch:
        inputs:
            version:
                description: Version of @balafla/core-components package, tag or sha
                required: false
                type: string

concurrency:
    group: ${{ github.workflow }}-${{ inputs.version || github.ref }}
    cancel-in-progress: true

jobs:
    params:
        uses: ./.github/workflows/resolve-demo-params.yml
        secrets: inherit
        with:
            version: ${{ inputs.version }}

    build-demo:
        needs: params
        uses: ./.github/workflows/build-demo.yml
        secrets: inherit
        with:
            ref: ${{ needs.params.outputs.ref }}

    deploy:
        needs: [build-demo, params]
        uses: ./.github/workflows/deploy-demo.yml
        secrets: inherit
        with:
            run-id: ${{ needs.build-demo.outputs.run-id }}
            dir: ${{ needs.params.outputs.dir }}
