name: Demo

on:
    workflow_call:
        inputs:
            version:
                description: Version of @alfalab/core-components package, tag, ref or sha
                required: false
                type: string
                default: ${{ github.ref }}
            directory:
                description: Directory to deploy demo
                required: false
                type: string
            deploy-repository:
                description: Repository
                required: false
                type: string
                default: ${{ github.repository }}
        outputs:
            run-id:
                description: Artifact workflow run id
                value: ${{ jobs.build-demo.outputs.run-id }}
    workflow_dispatch:
        inputs:
            version:
                description: Version of @alfalab/core-components package, tag or sha
                required: false
                type: string
            directory:
                description: Directory to deploy demo
                required: false
                type: string

concurrency:
    group: demo-${{ case(inputs.version == '', github.ref, inputs.version) }}
    cancel-in-progress: true

defaults:
    run:
        shell: bash

jobs:
    params:
        name: Resolve demo params
        uses: ./.github/workflows/resolve-demo-params.yml
        secrets: inherit
        with:
            version: ${{ inputs.version }}
            directory: ${{ inputs.directory }}

    sha:
        name: Resolve demo SHA
        needs: params
        runs-on: ubuntu-latest
        outputs:
            result: ${{ steps.find.outputs.result }}
        steps:
            - name: Checkout
              uses: actions/checkout@v6
              if: ${{ github.event_name == 'workflow_dispatch' }}
              with:
                  ref: ${{ needs.params.outputs.ref }}

            - name: Get SHA
              id: find
              if: ${{ github.event_name == 'workflow_dispatch' }}
              uses: actions/github-script@v8
              with:
                  result-encoding: string
                  script: |
                      const { stdout } = await exec.getExecOutput('git', ['rev-list', '-n', '1', 'HEAD']);

                      return stdout.trim();

    variants:
        name: Variants
        uses: ./.github/workflows/variants.yml

    build-demo:
        name: Build demo
        needs: [params, variants]
        strategy:
            matrix:
                include: ${{ fromJson(needs.variants.outputs.config) }}
        uses: ./.github/workflows/build-demo.yml
        secrets: inherit
        with:
            ref: ${{ needs.params.outputs.ref }}
            variant: ${{ matrix.variant }}
            artifact-name: ${{ matrix.variant }}

    deploy:
        name: Deploy demo
        needs: [build-demo, params, sha, variants]
        strategy:
            max-parallel: 1
            matrix:
                include: ${{ fromJson(needs.variants.outputs.config) }}
        uses: ./.github/workflows/deploy-demo.yml
        secrets: inherit
        with:
            run-id: ${{ needs.build-demo.outputs.run-id }}
            directory: ${{ case(matrix.variant == 'default', needs.params.outputs.directory, format('${0}-{1}', needs.params.outputs.directory, matrix.variant)) }}
            variant: ${{ matrix.variant }}
            artifact-name: ${{ matrix.variant }}
            deploy-repository: ${{ inputs.deploy-repository }}
            sha: ${{ needs.sha.outputs.result }}
