name: demo

on:
    workflow_call:
        inputs:
            version:
                description: Version of @alfalab/core-components package, tag, ref or sha
                required: false
                type: string
                default: ${{ github.ref }}
            directory:
                description: Directory deploy to
                required: false
                type: string
            deploy-repository:
                description: Repository
                required: false
                type: string
                default: ${{ github.repository }}
    workflow_dispatch:
        inputs:
            version:
                description: Version of @alfalab/core-components package, tag or sha
                required: false
                type: string
            directory:
                description: Directory deploy to
                required: false
                type: string

concurrency:
    group: demo-${{ case(inputs.version == '', github.ref, inputs.version) }}
    cancel-in-progress: true

defaults:
    run:
        shell: bash

jobs:
    params:
        uses: ./.github/workflows/resolve-demo-params.yml
        secrets: inherit
        with:
            version: ${{ inputs.version }}
            directory: ${{ inputs.directory }}
