name: main

on:
    pull_request:
        branches-ignore:
            - next
    push:
        branches:
            - master
            - next

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

defaults:
    run:
        shell: bash

jobs:
    upload-data:
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'pull_request' }}
        steps:
            - name: save pull request data
              run: |
                  mkdir -p pr
                  {
                      echo '${{ toJson(github.event.pull_request) }}'
                  } > pr/data.json

            - uses: actions/upload-artifact@v7
              with:
                  name: pr
                  path: pr

    demo:
        uses: ./.github/workflows/demo.yml
        secrets: inherit
        with:
            directory: ${{ case(github.event_name == 'pull_request', github.event.pull_request.number, github.ref_name) }}
            deploy-repository: ${{ github.event.pull_request.head.repo.full_name }}

    ci-ok:
        name: ci ok
        runs-on: ubuntu-latest
        if: always()
        needs: demo
        env:
            FAILURE: ${{ contains(join(needs.*.result, ','), 'failure') }}
        steps:
            - name: check for failure
              run: |
                  echo $FAILURE
                  if [ "$FAILURE" = "false" ]; then
                    exit 0
                  else
                    exit 1
                  fi
