name: main

on:
    pull_request:
        branches-ignore:
            - next
    push:
        branches:
            - master
            - next

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

defaults:
    run:
        shell: bash

jobs:
    variant:
        uses: ./.github/workflows/variant.yml
