name: main

on:
    pull_request:
        branches-ignore:
            - next
    push:
        branches:
            - master
            - next

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

defaults:
    run:
        shell: bash

jobs:
    build-demo:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                color: ${{ fromJson('[]') }}
        steps:
            - id: payload
              run: |
                  echo "${{ matrix.color }}"
