name: Beta release

on: workflow_dispatch

jobs:
    warning_and_fail:
        name: This workflow does nothing. Make sure ref is correct
        runs-on: ubuntu-latest
        steps:
            - name: Fail
              shell: bash
              run: |
                  exit 1
