name: Beta release

on: workflow_dispatch

jobs:
    warning_and_fail:
        runs-on: ubuntu-latest
        steps:
            - name: Print warinig and fail
              shell: bash
              run: |
                  echo "This workflow does nothing. Make sure ref is correct"
                  exit 1
