name: snapshot-release

on:
    workflow_call:
    workflow_dispatch:
        inputs:
            pull-request:
                description: Pull request number
                type: number
                required: true
            variant:
                description: Variant of core components
                required: false
                type: choice
                default: default
                options:
                    - default
                    - alfasans

concurrency:
    group: ${{ github.workflow }}-${{ inputs.pull-request }}-${{ inputs.variant }}
    cancel-in-progress: true

jobs:
    snapshot-release:
        name: snapshot release
        if: ${{ github.repository == 'core-ds/core-components' }}
        permissions:
            id-token: write # to use OpenID Connect token for trusted publishing (changesets/action)
        runs-on: ubuntu-latest
        outputs:
            published: ${{ steps.snapshot-release.outputs.published }}
            published-packages: ${{ steps.snapshot-release.outputs.published-packages }}
        env:
            CORE_COMPONENTS_VARIANT: ${{ inputs.variant }}
        steps:
            - name: get pull request data
              id: data
              uses: actions/github-script@v8
              with:
                  script: |
                      const { data } = await octokit.rest.pulls.get({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          pull_number: ${{ inputs.pull-request }},
                      });

                      if (data.head.repo.fork) {
                          core.setOutput('repository', data.head.repo.full_name);
                      }

                      core.setOutput('sha', data.head.sha);

            - uses: actions/checkout@v6
              with:
                  repository: ${{ steps.data.outputs.repository }}
                  ref: ${{ steps.data.outputs.sha }}
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: apply patch
              run: |
                  PATCH_SOURCE='variants/${{ inputs.variant }}.patch'

                  if [ -f "$PATCH_SOURCE" ]; then
                      git apply "$PATCH_SOURCE"
                  fi

            - uses: ./.github/actions/ci-setup
              env:
                  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

            - id: snapshot-release
              uses: core-ds/changesets-snapshot-release@v1
              with:
                  version: 'yarn version-packages:snapshot'
                  publish: 'yarn release:snapshot'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    comment:
        needs: snapshot-release
        if: ${{ fromJson(needs.snapshot-release.outputs.published) }}
        runs-on: ubuntu-latest
        permissions:
            issues: write # to post issue comments
        steps:
            - name: prepare comment
              id: prepare-comment
              uses: actions/github-script@v8
              env:
                  PUBLISHED_PACKAGES: ${{ needs.snapshot-release.outputs.published-packages }}
              with:
                  result-encoding: string
                  script: |
                      return JSON.parse(process.env.PUBLISHED_PACKAGES)
                          .map(({ name, version }, index) => `${index + 1}. \`${name}@${version}\``)
                          .join('\n\n');

            - name: create comment
              uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  issue-number: ${{ inputs.pull-request }}
                  body: |
                      ## Snapshot release

                      Successfully released the following packages:

                      ${{ steps.prepare-comment.outputs.result }}
                  reactions: rocket
