name: update-screenshots

on:
    workflow_dispatch:
        inputs:
            pull-request:
                description: Pull request number
                type: number
                required: true
            variant:
                description: Variant of core components
                required: false
                type: choice
                default: default
                options:
                    - default

concurrency:
    group: ${{ github.workflow }}-${{ inputs.pull-request }}-${{ inputs.variant }}
    cancel-in-progress: true

defaults:
    run:
        shell: bash

jobs:
    build-demo:
        uses: ./.github/workflows/build-demo.yml
        secrets: inherit
        with:
            variant: ${{ inputs.variant }}
            artifact-name: ${{ inputs.variant }}

    update:
        name: update screenshots (${{ inputs.variant }})
        runs-on: ubuntu-latest
        needs: build-demo
        env:
            CORE_COMPONENTS_VARIANT: ${{ inputs.variant }}
        steps:
            - id: repository
              uses: core-ds/core-components/.github/actions/parse-repository@master
              with:
                  repository: ${{ github.repository }}

            - name: generate app token
              id: generate-token
              uses: actions/create-github-app-token@v2
              with:
                  app-id: ${{ vars.APP_ID }}
                  private-key: ${{ secrets.APP_PRIVATE_KEY }}
                  owner: ${{ steps.repository.outputs.owner }}
                  repositories: ${{ steps.repository.outputs.repo }}

            - uses: actions/checkout@v6
              with:
                  repository: ${{ steps.repository.outputs.full-name }}
                  token: ${{ steps.generate-token.outputs.token }}
                  lfs: true

            - uses: ./.github/actions/ci-setup

            - name: download build
              uses: actions/download-artifact@v8
              with:
                  name: ${{ inputs.variant }}
                  path: build
                  run-id: ${{ needs.build-demo.outputs.run-id }}
                  github-token: ${{ secrets.GITHUB_TOKEN }}

            - name: update screenshots
              run: |
                  yarn test:screenshots -u

            - name: check git status
              id: have-changes
              uses: actions/github-script@v8
              with:
                  script: |
                      const { stdout } = await exec.getExecOutput('git', ['status', '--porcelain']);

                      return stdout.trim().length > 0;

            - name: update branch
              if: ${{ fromJson(steps.have-changes.outputs.result) }}
              uses: ./.github/actions/commit-and-push
              with:
                  message: 'test: updated screenshots'
