name: update screenshots

on: workflow_dispatch

jobs:
    update:
        name: update screenshots
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ github.repository == 'hextion/core-components' && secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}

            - name: update screenshots
              shell: bash
              run: |
                  echo $(date --iso-8601=seconds) > file.txt

            - name: check git status
              id: git-status
              uses: actions/github-script@v7
              with:
                  result-encoding: string
                  script: |
                      const { stdout } = await exec.getExecOutput('git', ['status', '--porcelain']);

                      return true;

            - name: setup git user
              if: ${{ github.repository == 'hextion/core-components' && steps.git-status.outputs.result == 'true' }}
              uses: ./.github/actions/setup-git-user
              with:
                  name: 'hextion'
                  email: '100ishundred@gmail.com'

            - name: update branch
              if: ${{ steps.git-status.outputs.result == 'true' }}
              uses: ./.github/actions/commit-and-push
              with:
                  setup-git-user: ${{ github.repository != 'hextion/core-components' }}
                  message: 'test: updated screenshots'
