name: update screenshots

on: workflow_dispatch

jobs:
    update:
        name: update screenshots
        runs-on: ubuntu-latest
        if: ${{ startsWith(github.ref, 'refs/heads/') }}
        steps:
            - uses: actions/checkout@v4
              with:
                  lfs: true

            - uses: ./.github/actions/ci-setup

            - name: update screenshots
              shell: bash
              run: |
                  yarn test:screenshots -u

            - name: check git status
              id: git-status
              uses: actions/github-script@v7
              with:
                  result-encoding: string
                  script: |
                      const { stdout } = await exec.getExecOutput('git', ['status', '--porcelain']);

                      return stdout.split('\n').some(line => /^\s+M\s+.*\.png$/.test(line));

            - name: update branch
              if: ${{ steps.git-status.outputs.result == 'true' }}
              uses: actions/github-script@v7
              with:
                  script: |
                      await exec.exec('git', ['config', 'user.name', `"github-actions[bot]"`]);

                      await exec.exec('git', [
                          'config',
                          'user.email',
                          `"41898282+github-actions[bot]@users.noreply.github.com"`,
                      ]);

                      await exec.exec('git', ['add', '.']);

                      const message = 'test: updated screenshots';

                      await exec.exec('git', ['commit', '-n', '-m', message]);

                      const branch = context.ref.replace('refs/heads/', '');

                      await exec.exec('git', ['push', 'origin', `HEAD:${branch}`]);
